import type { Metadata } from "next";
import { PageShell } from "@/components/PageShell";

export const metadata: Metadata = {
  title: "3° Conferenza Internazionale",
  description: "Conferenza Internazionale sulla Sindrome DDX3X — famiglie, medici, ricercatori e terapisti.",
};

export default function Page() {
  return (
    <PageShell title={"3° Conferenza Internazionale"} description={"Conferenza Internazionale sulla Sindrome DDX3X — famiglie, medici, ricercatori e terapisti."}>
      <div dangerouslySetInnerHTML={{ __html: "<p><strong><a href=\"/eventi/conferenza-internazionale\" target=\"_blank\" rel=\"noreferrer noopener\">Switch to English</a></strong></p>\r\n\r\n\r\n\r\n\r\n<img src=\"/media/wp/2026/02/DDX3X-Conference-5-6-May-2026-ITA-1.jpg\" alt=\"\" />\r\n\r\n<p><strong>Un evento globale per una comunità in crescita</strong></p>\r\n\r\n\r\n\r\n<p>Per la prima volta, l’Italia ha ospitato la Conferenza Internazionale sulla Sindrome DDX3X, un appuntamento che ha riunito famiglie, medici, ricercatori e terapisti provenienti da tutto il mondo.</p>\r\n\r\n\r\n\r\n<p>Due giornate di scambio e collaborazione per promuovere la ricerca scientifica, condividere esperienze e costruire nuove connessioni tra chi vive ogni giorno la realtà DDX3X e chi lavora per comprenderla e curarla.</p>\r\n\r\n\r\n\r\n\r\n<p><strong>Perché è importante</strong></p>\r\n\r\n\r\n\r\n<p>La conferenza nasce per:</p>\r\n\r\n\r\n\r\n<ul>\r\n<li>Diffondere le ultime scoperte scientifiche sulla sindrome DDX3X</li>\r\n\r\n\r\n\r\n<li>Offrire momenti di formazione e supporto alle famiglie</li>\r\n\r\n\r\n\r\n<li>Rafforzare la rete internazionale tra associazioni e centri di ricerca</li>\r\n\r\n\r\n\r\n<li>Promuovere inclusione, conoscenza e speranza</li>\r\n</ul>\r\n\r\n\r\n\r\n<p><strong>Un evento aperto a tutti</strong></p>\r\n\r\n\r\n\r\n<p>L’incontro si è tenuto sia in presenza che online in diretta streaming, con traduzione simultanea in italiano e inglese per garantire la partecipazione di tutti.</p>\r\n\r\n\r\n\r\n<p>Si sono tenutee sessioni dedicate alle famiglie, momenti di scambio tra associazioni europee e interventi scientifici condotti da esperti internazionali.</p>\r\n\r\n\r\n\r\n<h2>Programma</h2>\r\n\r\n\r\n\r\n<p><strong>Giorno 1</strong></p>\r\n\r\n\r\n\r\n<ul>\r\n<li>Registrazione partecipanti</li>\r\n\r\n\r\n\r\n<li>Saluti istituzionali</li>\r\n\r\n\r\n\r\n<li>Partecipazione dal vivo o in remoto di relatori di fama mondiale, specialisti e studiosi della sindrome</li>\r\n</ul>\r\n\r\n\r\n\r\n<p><strong>Giorno 2</strong></p>\r\n\r\n\r\n\r\n<ul>\r\n<li>Mattina: visita gratuita per tutti i partecipanti all’<em>Acquario di Genova</em></li>\r\n\r\n\r\n\r\n<li>Pomeriggio: consulti individuali gratuiti con gli esperti. In una <em>poster session</em> studenti e giovani ricercatori hanno presentato il loro lavoro sulla DDX3X. Genitori e scienziati hanno avuto l’opportunità di fare domande e confrontarsi direttamente con loro. Che preziosa occasione di networking!</li>\r\n</ul>\r\n\r\n\r\n\r\n<p><a href=\"/media/wp/2026/02/DDX3X-Conference-5-6-May-2026-ITA.pdf\" target=\"_blank\" rel=\"noreferrer noopener\">Scarica qui la brochure della conferenza</a></p>\r\n<p><a href=\"https://payhip.com/b/4c3GJ\">Registrazione integrale della Conferenza</a>, disponibile in 6 LINGUE!</p>" }} />
    </PageShell>
  );
}
