import type { Metadata } from "next";
import { PageShell } from "@/components/PageShell";

export const metadata: Metadata = {
  title: "Campagne di raccolta fondi",
  description: "Campagne attive e passate dell'Associazione DDX3X Italia ODV.",
};

export default function Page() {
  return (
    <PageShell title={"Campagne di raccolta fondi"} description={"Campagne attive e passate dell'Associazione DDX3X Italia ODV."}>
      <div dangerouslySetInnerHTML={{ __html: "<h2><strong>CAMPAGNA ATTIVA</strong></h2>\n\n<img src=\"/media/wp/2026/02/uova-di-pasqua-2026-2.png\" alt=\"\"/>\n<h2><strong>Uova di Pasqua solidali 2026</strong></h2>\n\n<p>Questa Pasqua puoi trasformare un dono tradizionale in un gesto di grande valore. Le nostre uova non sono solo buone: raccontano una storia di rarità, inclusione e speranza.</p>\n\n<p>Ogni acquisto contribuisce a:</p>\n\n<ul>\n<li>finanziare progetti dedicati alla sindrome DDX3X</li>\n\n<li>costruire una rete di famiglie e professionisti</li>\n\n<li>dare visibilità alle malattie genetiche rare.</li>\n</ul>\n\n<p>La campagna è CONCLUSA!</p>\n\n<p><strong>COME ACQUISTARE:</strong></p>\n\n<p>L'acquisto è semplice e sicuro:</p>\n\n<p><strong>Distributori ufficiali dell'associazione</strong> (volontari, referenti locali) utilizzano una modalità dedicata con pagamento posticipato.</p>\n\n<p>Se vuoi essere un distributore ufficiale o se non hai ricevuto le istruzioni contattaci!</p>\n\n<p><strong>Privati e sostenitori </strong>possono acquistare direttamente online con pagamento anticipato e ritirare le uova presso PUNTI DI RITIRO SELEZIONATI</p>\n\n<h2><strong>CAMPAGNE PRECEDENTI</strong></h2>\n\n<img src=\"/media/wp/2025/11/Sostieni-lAssociazione-DDX3X-1-1.png\" alt=\"\"/>\n<h2>Un gesto dolce che fa bene alle famiglie</h2>\n\n<p>Quest’anno, per il Natale, abbiamo scelto una modalità semplice e speciale per sostenere l’Associazione DDX3X ODV: la <strong>vendita solidale di creme spalmabili artigianali</strong>.</p>\n\n<p>Acquistando questi prodotti buoni e genuini, il ricavato sarà donato all’associazione e contribuirà a sostenere i progetti dedicati alle persone con sindrome DDX3X e alle loro famiglie: supporto quotidiano, informazione, iniziative di sensibilizzazione e attività di ricerca.</p>\n\n<p><strong>Con la Campagna di Natale 2025 abbiamo venduto 1.050 vasetti di cioccolata in oltre 20 città coinvolte!</strong></p>\n\n<p><strong>&nbsp;Perché partecipare?</strong></p>\n\n<ul>\n<li>Per fare un regalo goloso e di qualità.</li>\n\n<li>Per trasformare un acquisto di Natale in un gesto di solidarietà.</li>\n\n<li>Per aiutare concretamente la nostra comunità e i progetti che portiamo avanti ogni giorno.</li>\n</ul>\n\n<p><strong>&nbsp;Come acquistare</strong></p>\n\n<p><img src=\"https://fonts.gstatic.com/s/e/notoemoji/16.0/1f449/32.png\" alt=\"👉\">&nbsp;Per info e contatti rivolgersi a <strong>info@ddx3x.it</strong> oppure contattare Valentina: <strong>349 1433538</strong></p>\n\n<p></p>\n\n<p>Grazie di cuore a chi sceglierà di rendere questo Natale ancora più dolce e solidale.</p>\n\n<p>Insieme possiamo fare la differenza!</p>" }} />
    </PageShell>
  );
}
